### ISSUE TITLE
You cannot Ping other ore pools

### ISSUE THREAD

**Issue by worm001** [2miners/stratum-ping#10]
C:\>stratum-ping.exe -tls ru-eth.hiveon.net:24443
PING stratum ru-eth.hiveon.net (37.9.15.18) TLS port 24443
ru-eth.hiveon.net (37.9.15.18): seq=0, EOF
ru-eth.hiveon.net (37.9.15.18): seq=1, EOF
ru-eth.hiveon.net (37.9.15.18): seq=2, EOF
ru-eth.hiveon.net (37.9.15.18): seq=3, EOF

**Comment by rustam-iskenderov** [comment]
Try
`stratum-ping.exe -t stratum1 -tls ru-eth.hiveon.net:24443`

**Comment by worm001** [comment]
> Try `stratum-ping.exe -t stratum1 -tls ru-eth.hiveon.net:24443`

Thank you ~ it's OK.. However, it seems that this tool only supports ore pools with such protocols as Eth and etc. it is not enough to replace it with such protocols as xmr-jp1.nanopool.org: 14433.

stratum-ping.exe -t stratum1 -tls xmr-asia1.nanopool.org:14433
PING stratum xmr-asia1.nanopool.org (139.99.102.72) TLS port 14433 with credentials: 0x63a14c53f676f34847b5e6179c4f5f5a07f0b1ed:x
xmr-asia1.nanopool.org (139.99.102.72): seq=0, EOF
xmr-asia1.nanopool.org (139.99.102.72): seq=1, EOF
xmr-asia1.nanopool.org (139.99.102.72): seq=2, EOF
xmr-asia1.nanopool.org (139.99.102.72): seq=3, EOF
xmr-asia1.nanopool.org (139.99.102.72): seq=4, EOF

--- xmr-asia1.nanopool.org ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 8.4681987s

**Comment by hulitolku** [comment]
I use this scrupt in python, but not work for flockpool:
```
        stratum=subprocess.Popen(['D:\Download\MINING\stratum-ping-win-x64\stratum-ping.exe', ' -t stratum1 -tls eu.flockpool.com:5555 '],shell=True,stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE,encoding='cp866')    
        stdout, stderr = stratum.communicate()
```
i get:
`Failed to resolve host name: lookup  -t stratum2 -tls eu.flockpool.com: no such host`

if start this from BAT (stratum-ping.exe -t stratum1 -tls eu.flockpool.com:5555) its works fine:
```
--- eu.flockpool.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 6.1872129s
min/avg/max = 67.0603ms, 75.68644ms, 90.1708ms
```
