### ISSUE TITLE
Can't set more than 5 pings

### ISSUE THREAD

**Issue by rusty-labs** [2miners/stratum-ping#11]
running "stratum-ping.exe server:4444 -c 10" still gives 5 pings
To get a better average value it would be nice to run more than 5 pings.

**Comment by worm001** [comment]
-Just put the "-c 10" parameter in front of "server: 4444".

**Comment by rustam-iskenderov** [comment]
Still feels like a bug, usage does not say that server name parameter should be the last one, and usually order of parameters is not important for console apps.
