### ISSUE TITLE
High low

### ISSUE THREAD

**Issue by Rickytr23** [2miners/stratum-ping#2]
What is a good number to look for when pinning?

**Comment by edawtoc** [comment]
I think the the most important thing is that ping should be stable.
I think that ~30ms is perfect but even 100ms could be good if it is stable.

stratum-ping]$ ./build/bin/stratum-ping -tls eth.2miners.com:12020
PING stratum eth.2miners.com (51.195.105.101) TLS port 12020
eth.2miners.com (51.195.105.101): seq=0, time=30.844285ms
eth.2miners.com (51.195.105.101): seq=1, time=32.667843ms
eth.2miners.com (51.195.105.101): seq=2, time=32.037485ms
eth.2miners.com (51.195.105.101): seq=3, time=30.88984ms
eth.2miners.com (51.195.105.101): seq=4, time=32.420842ms

--- eth.2miners.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 5.509857194s
min/avg/max = 30.844285ms, 31.772059ms, 32.667843ms
