### ISSUE TITLE
how to build

### ISSUE THREAD

**Issue by 49handyman** [2miners/stratum-ping#3]
never used go before and tried, installed golang, make all didnt work, researched and didnt find any simple answers.

can you provide the linux instruction I'm using Ubuntu 18

**Comment by edawtoc** [comment]
I had to install gcc-go package for ArchLinux and then run 'make all' in the git root directory.

`stratum-ping]$ make all
build/env.sh go get -v ./...
github.com/2miners/stratum-ping
`

**Comment by 49handyman** [comment]
thanks ill try it
