### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by TheBeltMaker** [2miners/stratum-ping#8]
Ultra noob with linux here. Can someone please help me and tell me how I run this on Ubuntu?

**Comment by jasonhollis** [comment]
Team,

I'm not really a noob and I can't get this to install under Ubuntu or Windows.  Ideally the Rreadme should include install instructions or build a separatR text file?

**Comment by juanjlunar** [comment]
Go to https://go.dev/dl/.

Download the files for your OS.
Check if it is correctly installed with: go version in the command line.
Clone this repo in the location you want.
Then write in the command line: go run $yourLocation main.go $any-command-from-this-application.
Example: go run /home/stratum-ping/main.go -tls eth.2miners.com:12020. (Asumming you cloned the project in /home)
