### ISSUE TITLE
High stratum ping but low normal ping

### ISSUE THREAD

**Issue by ptykamikaze** [2miners/stratum-ping#9]
Hello I'm testing the stratum ping to your servers but I see the stratum ping is very high compared to the normal ping of the IP, can you tell me that can be wrong? THanks

>stratum-ping.exe solo-eth.2miners.com:6060
PING stratum solo-eth.2miners.com (51.195.88.16) port 6060
solo-eth.2miners.com (51.195.88.16): seq=0, time=146.0329ms
solo-eth.2miners.com (51.195.88.16): seq=1, time=163.0371ms
solo-eth.2miners.com (51.195.88.16): seq=2, time=157.035ms
solo-eth.2miners.com (51.195.88.16): seq=3, time=162.0371ms
solo-eth.2miners.com (51.195.88.16): seq=4, time=147.0335ms

--- solo-eth.2miners.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 6.5494755s
min/avg/max = 146.0329ms, 155.03512ms, 163.0371ms

>ping 51.195.88.16

Pinging 51.195.88.16 with 32 bytes of data:
Reply from 51.195.88.16: bytes=32 time=156ms TTL=47
Reply from 51.195.88.16: bytes=32 time=156ms TTL=47
Reply from 51.195.88.16: bytes=32 time=156ms TTL=47
Reply from 51.195.88.16: bytes=32 time=156ms TTL=47

Ping statistics for 51.195.88.16:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 156ms, Maximum = 156ms, Average = 156ms

**Comment by slavikus** [comment]
Correct me if I am wrong, but both probes pasted above feature an average of 150-160 ms, so there is almost no difference between two methods?

**Comment by ptykamikaze** [comment]
Sorry you are right!. My bad
